#!/usr/bin/env python3
# data/jobs/, data/clients/, data/vendors/, settings.json を読んで ui/data.js を生成
import json
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
UI = ROOT / "ui"

TICKTICK_BIN = Path.home() / "ticktick/bin/ticktick"
TICKTICK_PROJECT_PID = "69e64fb64892e90a4be4cbaf"  # 💼仕事


def load_json(path: Path):
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def collect(dir_path: Path):
    if not dir_path.exists():
        return []
    return [load_json(p) for p in sorted(dir_path.glob("*.json"))]


def collect_minutes(dir_path: Path):
    """議事録一覧。data.js を肥大化させないため transcript / raw_input は除外（詳細はAPI経由で取得）。"""
    if not dir_path.exists():
        return []
    items = []
    for p in sorted(dir_path.glob("*.json")):
        try:
            data = load_json(p)
        except Exception:
            continue
        slim = {k: v for k, v in data.items() if k not in ("transcript", "raw_input")}
        items.append(slim)
    items.sort(key=lambda x: (x.get("date", ""), x.get("time", "")), reverse=True)
    return items


def get_ticktick_progress(task_id, project_id=TICKTICK_PROJECT_PID):
    """TickTickタスクの進捗情報を返す。
    戻り値: {"current_item": str|None, "done": int, "total": int}
    取得失敗時: {"current_item": None, "done": 0, "total": 0}
    """
    empty = {"current_item": None, "done": 0, "total": 0}
    if not task_id or not TICKTICK_BIN.exists():
        return empty
    try:
        result = subprocess.run(
            [str(TICKTICK_BIN), "items", task_id, "--project", project_id],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0:
            return empty

        current_item = None
        done = 0
        total = 0

        for line in result.stdout.splitlines():
            if "[x]" in line:
                done += 1
                total += 1
            elif "[ ]" in line:
                total += 1
                if current_item is None:
                    # 最初の未チェック項目を取得
                    m = re.search(r"\[\s*\]\s+(.+?)\s+item_id=", line)
                    if m:
                        current_item = m.group(1).strip()
                    else:
                        m = re.search(r"\[\s*\]\s+(.+)", line)
                        if m:
                            current_item = m.group(1).strip()

        return {"current_item": current_item, "done": done, "total": total}
    except Exception:
        return empty


def enrich_jobs_with_ticktick(jobs: list) -> None:
    """各jobに ticktick_current_item / ticktick_done / ticktick_total を付与する（並列取得）。"""
    targets = [(i, job) for i, job in enumerate(jobs) if job.get("TickTick_task_id")]
    results = {}  # index → progress dict

    def fetch(idx_job):
        idx, job = idx_job
        return idx, get_ticktick_progress(job["TickTick_task_id"])

    with ThreadPoolExecutor(max_workers=8) as ex:
        futures = {ex.submit(fetch, t): t for t in targets}
        for fut in as_completed(futures):
            idx, prog = fut.result()
            results[idx] = prog

    for i, job in enumerate(jobs):
        prog = results.get(i, {"current_item": None, "done": 0, "total": 0})
        job["ticktick_current_item"] = prog["current_item"]
        job["ticktick_done"]         = prog["done"]
        job["ticktick_total"]        = prog["total"]
        if job.get("TickTick_task_id") and prog["total"] > 0:
            pct = int(prog["done"] / prog["total"] * 100)
            item = prog["current_item"] or "（全工程完了）"
            print(f"  #{job.get('制作番号','?')} {pct}% ({prog['done']}/{prog['total']}) → {item}")


def main():
    settings = load_json(ROOT / "settings.json")
    jobs = collect(DATA / "jobs")
    clients = collect(DATA / "clients")
    vendors = collect(DATA / "vendors")
    minutes = collect_minutes(DATA / "minutes")

    print("TickTick から現在の工程を取得中...")
    enrich_jobs_with_ticktick(jobs)

    payload = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "settings": settings,
        "jobs": jobs,
        "clients": clients,
        "vendors": vendors,
        "minutes": minutes,
    }

    UI.mkdir(exist_ok=True)
    out = UI / "data.js"
    with out.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_data_js.py — do not edit manually\n")
        f.write("window.IDEARNEST = ")
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write(";\n")

    print(f"✅ {out} を生成しました")
    print(f"   案件: {len(jobs)}件 / クライアント: {len(clients)}社 / 外注先: {len(vendors)}社 / 議事録: {len(minutes)}件")


if __name__ == "__main__":
    main()
